// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unstickd.Data;

#nullable disable

namespace Unstickd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260117191107_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Unstickd.Models.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("Unstickd.Models.StoryPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("Unstickd.Models.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundTexture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FontName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpritePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Themes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundTexture = "white",
                            Description = "The Queen's Rose Garden",
                            FontName = "Alice",
                            Name = "Wonderland",
                            PrimaryColor = "#eec4d5",
                            SecondaryColor = "#ba0d2d",
                            SpritePath = "images/cheshire.png"
                        },
                        new
                        {
                            Id = 2,
                            BackgroundTexture = "#f0f0f0",
                            Description = "The Hidden Moorland Oasis",
                            FontName = "Goudy Bookletter 1911",
                            Name = "Secret Garden",
                            PrimaryColor = "#8fb35d",
                            SecondaryColor = "#5d8aa8",
                            SpritePath = "images/robin.png"
                        },
                        new
                        {
                            Id = 3,
                            BackgroundTexture = "#0d1b2a",
                            Description = "Neverland at Twilight",
                            FontName = "Cinzel Decorative",
                            Name = "Neverland",
                            PrimaryColor = "#191970",
                            SecondaryColor = "#ffd700",
                            SpritePath = "images/pan.png"
                        },
                        new
                        {
                            Id = 4,
                            BackgroundTexture = "#fafff0",
                            Description = "The Emerald City",
                            FontName = "Rye",
                            Name = "Oz",
                            PrimaryColor = "#50c878",
                            SecondaryColor = "#daa520",
                            SpritePath = "images/toto.png"
                        },
                        new
                        {
                            Id = 5,
                            BackgroundTexture = "#f5deb3",
                            Description = "Sun-Bleached Map",
                            FontName = "Pirata One",
                            Name = "Treasure Island",
                            PrimaryColor = "#d2b48c",
                            SecondaryColor = "#000080",
                            SpritePath = "images/parrot.png"
                        },
                        new
                        {
                            Id = 6,
                            BackgroundTexture = "#fdf5e6",
                            Description = "Wind in the Willows",
                            FontName = "WindSong",
                            Name = "Riverbank",
                            PrimaryColor = "#8b4513",
                            SecondaryColor = "#9dc183",
                            SpritePath = "images/mole.png"
                        },
                        new
                        {
                            Id = 7,
                            BackgroundTexture = "#fff0f5",
                            Description = "The Velveteen Rabbit",
                            FontName = "Sniglet",
                            Name = "Nursery",
                            PrimaryColor = "#f5f5dc",
                            SecondaryColor = "#b76e79",
                            SpritePath = "images/rabbit.png"
                        },
                        new
                        {
                            Id = 8,
                            BackgroundTexture = "#fff8dc",
                            Description = "Geppetto's Workshop",
                            FontName = "Geostar Fill",
                            Name = "Workshop",
                            PrimaryColor = "#deb887",
                            SecondaryColor = "#6495ed",
                            SpritePath = "images/cricket.png"
                        });
                });

            modelBuilder.Entity("Unstickd.Models.Story", b =>
                {
                    b.HasOne("Unstickd.Models.Theme", "Theme")
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Unstickd.Models.StoryPage", b =>
                {
                    b.HasOne("Unstickd.Models.Story", "Story")
                        .WithMany("Pages")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Unstickd.Models.Story", b =>
                {
                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
